repos:
  - repo: local
    hooks:
      - id: codespell
        name: "python: codespell"
        entry: codespell
        language: system
        pass_filenames: false

  # Standard pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: mixed-line-ending
        args: ["--fix=lf"]
        description: Forces to replace line ending by the UNIX 'lf' character.
        exclude: '(^website/public/images/|^kotlin/android/gradlew.bat|^rust/windows-client/wintun/)'
      - id: check-yaml
      - id: check-merge-conflict
      - id: end-of-file-fixer
        exclude: ^website/public/images/
      - id: trailing-whitespace
        exclude: ^website/public/images/
      - id: check-merge-conflict
      - id: no-commit-to-branch
        args:
          - -b
          - master
          - --pattern
          - '^(?!((chore|feat|feature|bug|fix|build|ci|docs|style|refactor|perf|test|revert)\/[@a-zA-Z0-9\-\.\/]+)$).*'