roles:
  - name: CI
    comment: CI role, do not drop
  - name: EMPTY
    comment: This role is intentionally left empty
  - name: STATIC_ROLE
    comment: Static role
  - name: ~@#$%^&*()_+
    owner: ACCOUNTADMIN
    comment: This role has some issues

databases:
  - name: static_database

role_grants:
  - role: CI
    roles:
      - SYSADMIN
  - role: EMPTY
    roles:
      - SYSADMIN
  - role: static_role
    roles:
      - SYSADMIN

network_rules:
  - name: static_network_rule
    type: HOST_PORT
    value_list: ["example.com:443"]
    mode: EGRESS
    database: static_database
    schema: public

# secrets:
#   - name: static_secret
#     type: PASSWORD
#     username: someuser
#     password: somepass


grants:
  - GRANT USAGE ON WAREHOUSE STATIC_WAREHOUSE TO ROLE CI
  - GRANT USAGE ON DATABASE static_database TO ROLE CI
  - GRANT USAGE ON SCHEMA static_database.static_schema TO ROLE CI
  - GRANT SELECT ON TABLE static_database.public.static_table TO ROLE CI
  - GRANT SELECT ON VIEW static_database.public.static_view TO ROLE CI
  - GRANT READ ON STAGE static_database.public.static_stage TO ROLE CI


schemas:
  - name: static_schema
    database: static_database

stages:
  - name: static_stage
    type: INTERNAL
    directory:
      enable: true

streams:
  - name: static_stream
    database: static_database
    schema: public
    on_table: static_database.public.static_table
    copy_grants: false

tables:
  - name: static_table
    columns:
      - name: id
        data_type: NUMBER(38,0)
    change_tracking: true


views:
  - name: static_view
    columns:
      - name: id
        data_type: NUMBER(38,0)
    as_: SELECT id FROM STATIC_DATABASE.public.static_table
    change_tracking: true
    requires:
      - name: static_table
        resource_type: table

warehouses:
  - name: static_warehouse
  - name: CI
    warehouse_size: XSMALL

compute_pools:
  - name: static_compute_pool
    min_nodes: 1
    max_nodes: 1
    initially_suspended: true
    auto_resume: false
    auto_suspend_secs: 60
    instance_family: CPU_X64_XS
  
security_integrations:
  - name: SNOWSERVICES_INGRESS_OAUTH
    type: OAUTH
    oauth_client: snowservices_ingress
    enabled: true
  - name: STATIC_SECURITY_INTEGRATION
    type: api_authentication
    auth_type: OAUTH2
    oauth_client_auth_method: CLIENT_SECRET_POST
    oauth_client_id: 'sn-oauth-134o9erqfedlc'
    oauth_client_secret: 'eb9vaXsrcEvrFdfcvCaoijhilj4fc'
    oauth_token_endpoint: 'https://myinstance.service-now.com/oauth_token.do'
    enabled: true

