name: Build and release the Python Package

on:
  push:
    branches:
    - main
    paths-ignore:
    - version.md
  workflow_call:
    secrets:
      PYPI_USERNAME:
        required: true
      PYPI_PASSWORD:
        required: true

jobs:
  bump-version:
    name: Bump package version
    if: "!contains(github.event.head_commit.message, 'Bump version')"
    runs-on: ubuntu-20.04
    steps:
    - name: actions/checkout
      uses: actions/checkout@v4
      with:
          persist-credentials: false
    - name: current_version
      run: echo "current_version=$(grep '# version' version.md | cut -d ' ' -f3)" >> $GITHUB_ENV
    - name: FragileTech/bump-version
      uses: FragileTech/bump-version@main
      with:
        current_version: "${{ env.current_version }}"
        files: version.md
        commit_name: Titan Systems Bot
        commit_email: info@applytitan.com
        login: titan-systems-bot
        token: "${{ secrets.BOT_TOKEN }}"

  create-tag:
    needs: bump-version
    runs-on: ubuntu-20.04
    steps:
      - name: actions/checkout
        uses: actions/checkout@v4
      - name: Create Tag
        run: |
          new_version=$(grep '# version' version.md | cut -d ' ' -f3)
          git tag v$new_version
          git push origin v$new_version

  build-and-upload:
    needs: create-tag
    runs-on: ubuntu-20.04
    steps:
      - name: actions/checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Build and upload to PyPI
        run: |
          make submit
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}