name: Bump version workflow

on:
  push:
    branches:
    - main
    paths-ignore:
    - version.md

jobs:
  bump-version:
    name: Bump package version
    if: "!contains(github.event.head_commit.message, 'Bump version')"
    runs-on: ubuntu-20.04
    steps:
    - name: actions/checkout
      uses: actions/checkout@v4
      with:
          persist-credentials: false
    - name: current_version
      run: echo "current_version=$(grep '# version' version.md | cut -d ' ' -f3)" >> $GITHUB_ENV
    - name: FragileTech/bump-version
      uses: FragileTech/bump-version@main
      with:
        current_version: "${{ env.current_version }}"
        files: version.md
        commit_name: Titan Systems Bot
        commit_email: info@applytitan.com
        login: titan-systems-bot
        token: "${{ secrets.BOT_TOKEN }}"
