name: Test and Lint Python Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_call:
    secrets:
      TEST_SNOWFLAKE_ACCOUNT:
        required: true
      TEST_SNOWFLAKE_USER:
        required: true
      TEST_SNOWFLAKE_PASSWORD:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Create a virtual environment
      run: |
        python -m venv .venv
    - name: Install dependencies
      run: |
        source ./.venv/bin/activate
        python -m pip install --upgrade pip
        make install-dev
    - name: Run checks (linter, code style, tests)
      run: |
        source ./.venv/bin/activate
        make check
  integration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - environment: snowflake-aws-standard
            edition: standard
          - environment: snowflake-aws-enterprise
            edition: enterprise
    environment: ${{ matrix.environment }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Create a virtual environment
      run: |
        python -m venv .venv
    - name: Install dependencies
      run: |
        source ./.venv/bin/activate
        python -m pip install --upgrade pip
        make install-dev
    - name: Run integration tests
      run: |
        source ./.venv/bin/activate
        make integration EDITION=${{ matrix.edition }}
      env:
        TEST_SNOWFLAKE_ACCOUNT: ${{ secrets.TEST_SNOWFLAKE_ACCOUNT }}
        TEST_SNOWFLAKE_USER: ${{ secrets.TEST_SNOWFLAKE_USER }}
        TEST_SNOWFLAKE_PASSWORD: ${{ secrets.TEST_SNOWFLAKE_PASSWORD }}
        TEST_SNOWFLAKE_ROLE: ACCOUNTADMIN